services:
  backend:
    image: trietle123/backend-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    image: lecongthuan/ct250-frontend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: