services:
  backend:
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    command: npm run start # hoặc nodemon src/server.ts
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  # db:
  #   image: mysql:8
  #   # restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
# volumes:
#   db_data:
  # --- SERVICE RASA CORE (Server) ---
  rasa:
    image: my-rasa-image:latest
    build:
      context: ./BotRasa         # <--- TRỎ VÀO THƯ MỤC CHỨA RASA
      dockerfile: Dockerfile     # Tên file Dockerfile trong thư mục BotRasa
    ports:
      - "5005:5005"
    command: rasa run --enable-api --cors "*" --debug
    volumes:
      # Mount model từ thư mục con ra ngoài để giữ lại model sau khi train
      - ./BotRasa/models:/app/models  
      # (Tùy chọn) Mount config để sửa file yml mà không cần rebuild
      - ./BotRasa/config.yml:/app/config.yml 
      - ./BotRasa/domain.yml:/app/domain.yml
      - ./BotRasa/data:/app/data
      - ./BotRasa/endpoints.yml:/app/endpoints.yml
      - ./BotRasa/credentials.yml:/app/credentials.yml
    depends_on:
      - action_server

  # --- SERVICE RASA ACTION SERVER ---
  action_server:
    image: my-rasa-image:latest
    build:
      context: ./BotRasa         # <--- Dùng chung context/image với service rasa
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    command: rasa run actions
    volumes:
      # Mount thư mục actions để khi bạn sửa code python, nó tự cập nhật (nếu có auto-reload)
      - ./BotRasa/actions:/app/actions
