services:
  backend:
    image: trietle123/backend-app:latest
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app:rw
      - /app/node_modules
    ports:
      - "3000:3000"
    # command: npm run start # hoặc nodemon src/server.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    image: lecongthuan/ct250-frontend:latest
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app:rw
      - /app/node_modules
    ports:
      - "3001:3001"
    # command: npm run dev
    environment:
      - NODE_ENV=development
  db:
    image: mysql:8
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
