services:
  backend:
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start # hoặc nodemon src/server.ts
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
  # db:
  #   image: mysql:8
  #   # restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
# volumes:
#   db_data:
